stages:
  - build



# Common build settings
.common_build: &ref_common_build
  variables:
    CI_DEBUG_TRACE: "false"
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_IMAGE_VER: "v0.6"
    DOCKER_TAG: "hub.silentcircle.org/eng/sc-android-build:${DOCKER_IMAGE_VER}"
    # All these are required by the build script
    BUILD_NUMBER_PREFIX: "${CI_COMMIT_REF_SLUG}"
    WORKSPACE: "${CI_PROJECT_DIR}"
    GRADLE_USER_HOME: "$WORKSPACE/.gradle"
    SRC_ROOT: "$WORKSPACE"
    JNI_ROOT: "${WORKSPACE}/silentphone2/support"
    BUILD_SCRIPT: "silentphone2/.build-release/android-build.sh"
  # We want all the files downloaded by Gradle to persist across builds
  # for the same branch or tag.
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
      - "${GRADLE_USER_HOME}/caches"
      - "${GRADLE_USER_HOME}/wrapper"
  image: "${DOCKER_TAG}"
  tags:
    - docker-debian
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
    when: on_success
    expire_in: 8 weeks
    paths:
      - silentphone2/build/outputs
  allow_failure: false



# Development build
dev_build_job:
  stage: build
  except: # Except any tags of format vN.M+ or VN.M-rcX
    - /^v\d+\.\d+(\.\d+)*(-rc\d+)?$/
  script:
    - bash -xv $BUILD_SCRIPT DEVELOP
  <<: *ref_common_build


# Beta/RC build
beta_build_job:
  stage: build
  only:
    - /^v\d+\.\d+(\.\d+)*-rc\d+$/
  script:
    - bash -xv $BUILD_SCRIPT RELEASE
  <<: *ref_common_build



  # We don't have a prod build job. Prod builds
  # are rc (beta) builds that have passed QA and
  # are deemed ready for release. They don't get rebuilt
  # because that's risky and unnecessary.
